name: CI

on:
  workflow_dispatch:
  push:
    branches: ["develop"]
  pull_request:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm install --legacy-peer-deps
      - run: npm run build --workspace=scratch-blocks  # if scratch-blocks supports this
      - run: npm run build
